# 📊 Análise de Dados Musicais - Spotify & YouTube

## 🎯 Contexto do Projeto

**Você foi contratado pela Mateus Music** como Cientista de Dados para analisar o catálogo musical da empresa. Sua missão é explorar a base de dados contendo **mais de 20.000 músicas** e extrair insights valiosos sobre o desempenho dos artistas nas plataformas Spotify e YouTube.

A empresa precisa entender:
- Quem são os artistas mais relevantes
- Quais músicas performam melhor
- Como otimizar investimentos em marketing digital

## 📁 Sobre a Base de Dados

### Características Principais:
- **+20.000 músicas** no catálogo completo
- Dados de **Streams no Spotify** 
- Dados de **Views no YouTube**
- **Links dos vídeos** do YouTube para cada música
- **Metadados completos** de artistas e faixas

### 1. Importe o Pandas e mostre as informações gerais do dataframe

In [3]:
!pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in C:\Users\PROG05\AppData\Roaming\Python\Python313\site-packages (24.0.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

df = pd.read_parquet("Dados_Artistas.parquet")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            20718 non-null  str
 1   Url_spotify       20718 non-null  str
 2   Track             20718 non-null  str
 3   Album             20718 non-null  str
 4   Album_type        20718 non-null  str
 5   Uri               20718 non-null  str
 6   Danceability      20716 non-null  float64
 7   Energy            20716 non-null  float64
 8   Key               20716 non-null  float64
 9   Loudness          20716 non-null  float64
 10  Speechiness       20716 non-null  float64
 11  Acousticness      20716 non-null  float64
 12  Instrumentalness  20716 non-null  float64
 13  Liveness          20716 non-null  float64
 14  Valence           20716 non-null  float64
 15  Tempo             20716 non-null  float64
 16  Duration_ms       20716 non-null  float64
 17  Url_youtube       20248 non-null  str
 18  Title             20248 non-null  str
 19  Channel           20248 non-null  str
 20  Views             20248 non-null  float64
 21  Likes             20177 non-null  float64
 22  Comments          20149 non-null  float64
 23  Description       19842 non-null  str
 24  Licensed          20248 non-null  object
 25  official_video    20248 non-null  object
 26  Stream            20142 non-null  float64
dtypes: float64(15), object(2), str(10)
memory usage: 31.0+ MB

### 2. Mostre as cinco primeiras linhas do dataframe

In [ ]:
df.head()

### 3. Vamos ver quais os artistas temos em nosso df e contar quantos artistas diferentes temos no nosso dataset

In [8]:
artistas_unicos = df.Artist.unique()
quantidade_artistas = artistas_unicos.size
df

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,0.582,0.926,5.0,-6.344,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote\n\nJUST DANCE...,True,True,9.227144e+06
20714,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,0.531,0.936,4.0,-1.786,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote\n\nSET FIRE T...,True,True,1.089818e+07
20715,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,0.443,0.830,4.0,-4.679,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,Provided to YouTube by Routenote\n\nOUTSIDE HA...,True,True,6.226110e+06
20716,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,spotify:track:5EyErbpsugWliX006eTDex,0.417,0.767,9.0,-4.004,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,Provided to YouTube by Routenote\n\nONLY GIRL ...,True,True,6.873961e+06
20717,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,0.498,0.938,6.0,-4.543,...,https://www.youtube.com/watch?v=zau0dckCFi0,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote\n\nMISS YOU H...,True,True,5.695584e+06

### 4. Quais os 10 artistas com mais musicas em nosso dataset?

In [16]:
### vamos verifcar os artistas com mais musicas na lista.

df.Artist.value_counts()

Artist
Gorillaz                 10
Red Hot Chili Peppers    10
50 Cent                  10
Metallica                10
Coldplay                 10
                         ..
Shubh                     6
NewJeans                  6
Jimin                     3
Bootie Brown              1
Stars Music Chile         1
Name: count, Length: 2079, dtype: int64

### 5. Quais as 5 músicas com musicas com mais views no youtube?

In [20]:
### quero mostrar as 5 musicas com mais views no youtube
df.sort_values(by="Views", ascending=False)

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
1147,Luis Fonsi,https://open.spotify.com/artist/4V8Sr092TqfHkf...,Despacito,VIDA,album,spotify:track:6habFhsOp2NvshLv26DqMb,0.655,0.7970,2.0,-4.787,...,https://www.youtube.com/watch?v=kJQP7kiw5Fk,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,8.079649e+09,50788652.0,4252791.0,“Despacito” disponible ya en todas las platafo...,True,True,1.506598e+09
365,Daddy Yankee,https://open.spotify.com/artist/4VMYDCV2IEDYJA...,Despacito,VIDA,album,spotify:track:6habFhsOp2NvshLv26DqMb,0.655,0.7970,2.0,-4.787,...,https://www.youtube.com/watch?v=kJQP7kiw5Fk,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,8.079647e+09,50788626.0,4252791.0,“Despacito” disponible ya en todas las platafo...,True,True,1.506598e+09
12452,Ed Sheeran,https://open.spotify.com/artist/6eUKZXaKkcviH0...,Shape of You,÷ (Deluxe),album,spotify:track:7qiZfU4dY1lWllzX7mPBI3,0.825,0.6520,1.0,-3.183,...,https://www.youtube.com/watch?v=JGwWNGJdvx8,Ed Sheeran - Shape of You (Official Music Video),Ed Sheeran,5.908398e+09,31047780.0,1130327.0,The official music video for Ed Sheeran - Shap...,True,True,3.362005e+09
14580,Charlie Puth,https://open.spotify.com/artist/6VuMaDnrHyPL1p...,See You Again (feat. Charlie Puth),See You Again (feat. Charlie Puth),single,spotify:track:2JzZzZUQj3Qff7wapcbKjc,0.689,0.4810,10.0,-7.503,...,https://www.youtube.com/watch?v=RgKAFK5djSk,Wiz Khalifa - See You Again ft. Charlie Puth [...,Wiz Khalifa Music,5.773798e+09,40147674.0,2127346.0,Download the new Furious 7 Soundtrack Deluxe V...,True,True,1.521255e+09
12469,Wiz Khalifa,https://open.spotify.com/artist/137W8MRPWKqSmr...,See You Again (feat. Charlie Puth),See You Again (feat. Charlie Puth),single,spotify:track:2JzZzZUQj3Qff7wapcbKjc,0.689,0.4810,10.0,-7.503,...,https://www.youtube.com/watch?v=RgKAFK5djSk,Wiz Khalifa - See You Again ft. Charlie Puth [...,Wiz Khalifa Music,5.773797e+09,40147618.0,2127345.0,Download the new Furious 7 Soundtrack Deluxe V...,True,True,1.521255e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20090,Guilherme & Benuto,https://open.spotify.com/artist/6m6e7D2TnV0aYM...,Pulei na Piscina - Ao Vivo,DRIVE-IN (Ao Vivo),album,spotify:track:73wHYd9m8G8KJenerT2jOs,0.582,0.7740,3.0,-5.199,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,1.381329e+08
20091,Guilherme & Benuto,https://open.spotify.com/artist/6m6e7D2TnV0aYM...,Batom Vermelho,Batom Vermelho,single,spotify:track:72az3XEy1rALhVuoepsFpl,0.654,0.9010,11.0,-3.212,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2.386482e+07
20092,Guilherme & Benuto,https://open.spotify.com/artist/6m6e7D2TnV0aYM...,Declaração pro Bar - Ao Vivo,"Amando, Bebendo e Sofrendo (Ao Vivo) - EP 3",single,spotify:track:48CAeajgzcGJaVUSsXd7h0,0.679,0.7670,2.0,-5.058,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,8.942449e+07
20093,Fred again..,https://open.spotify.com/artist/4oLeXFyACqeem2...,Rumble,Rumble,single,spotify:track:1GfBLbAhZUWdseuDqhocmn,0.810,0.8360,1.0,-7.721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2.472762e+07
20282,Solfeggio Healing Frequencies MT,https://open.spotify.com/artist/5R9eOlQf7HGzD6...,528 Hz Emotional Healing,528 Hz Meditation Music,album,spotify:track:5fOf105Dd3ZJAJZchLa5ce,0.166,0.0438,0.0,-30.378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,3.690125e+07

### 6. Quais os 5 artistas com mais streams no spotify?

In [27]:
### Quais os 5 artistas com mais streams no spotify?
stream_por_artista = df.groupby("Artist")["Stream"].sum()
stream_por_artista.sort_values(ascending=False).head(5)

Artist
Post Malone     1.525126e+10
Ed Sheeran      1.439488e+10
Dua Lipa        1.340808e+10
XXXTENTACION    1.322435e+10
The Weeknd      1.303197e+10
Name: Stream, dtype: float64

### 7. Vamos converter e salvar o arquivo com parquet, para subir no github

In [29]:
### vamos converter o arquivo para parquet
df.to_parquet('Dados_Artistas.parquet', index=False)
df.to_csv("Análise Spotify")